name: Patient Management System

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
      - "9094:9094"

    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

    networks:
      - internal

  # Other services
  auth-service:
    extends:
      file: ./Auth Service/docker-compose.yml
      service: auth-service
    networks:
      - internal

  auth-service-db:
    extends:
      file: ./Auth Service/docker-compose.yml
      service: auth-service-db
    networks:
      - internal

  patient-service:
    extends:
      file: ./Patient Service/docker-compose.yml
      service: patient-service
    networks:
      - internal

  patient-service-db:
    extends:
      file: ./Patient Service/docker-compose.yml
      service: patient-service-db
    networks:
      - internal

  billing-service:
    extends:
      file: ./Billing Service/docker-compose.yml
      service: billing-service
    networks:
      - internal

  analytics-service:
    extends:
      file: ./Analytics Service/docker-compose.yml
      service: analytics-service
    networks:
      - internal

  api-gateway:
    extends:
      file: ./API Gateway/docker-compose.yml
      service: api-gateway
    networks:
      - internal

volumes:
  kafka_data:
  auth_postgres_data:
  patient_postgres_data:

networks:
  internal:
    name: internal
    driver: bridge
