services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: analytics-service:latest
    container_name: analytics-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
